---
- hosts: db
  become: true
  gather_facts: yes
  
  tasks:
   - name: Package Installation
     yum:
       name: "{{item}}"
       state: present
#    with_items:
     loop:
       - curl
       - finger
       - wget
       - httpd
       - ntp 